---
name: Build and Deploy React App to S3
on:
  workflow_dispatch:

  #  push:
  #   branches:
  #   - login
  # pull_request:
  #   branches:
  #   - main
  

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
   
    steps:
      - name: Checking out code 
        uses: actions/checkout@main

      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Installing dependencies
        working-directory: ngx-p1-frontend
        run: npm install

      - name: Building project
        working-directory: ngx-p1-frontend
        run: npm run build
        env:
         CI: false

      - name: Run tests if present
        run: npm run test --if-present

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to S3 bucket
        run: aws s3 sync ./dist/ s3://project1-react-frontend --delete




